# coding: utf-8

"""
    Gravscale Public Restful API

    API pública da Gravscale oferece aos usuários a capacidade de se autenticar, visualizar e contratar produtos disponíveis, enviar dados de contratação, escolher formas de pagamento e gerenciar nossos produtos. Além disso, os usuários podem cadastrar chaves SSH e realizar o deploy de um sistema operacional de forma eficiente e segura. Esta API foi projetado para simplificar e agilizar o gerenciamento de recursos proporcionando que a a Gravscale forneça uma experiência integrada e intuitiva para os usuários.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gravscale.api.network_api import NetworkApi


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworkApi()

    def tearDown(self) -> None:
        pass

    def test_create_public_ip(self) -> None:
        """Test case for create_public_ip

        Create Public Ip
        """
        pass

    def test_deallocate_public_ip(self) -> None:
        """Test case for deallocate_public_ip

        Deallocate Public Ip
        """
        pass

    def test_list_all_public_ips(self) -> None:
        """Test case for list_all_public_ips

        List Public Ips
        """
        pass


if __name__ == "__main__":
    unittest.main()
