# coding: utf-8

"""
    Gravscale Public Restful API

    API pública da Gravscale oferece aos usuários a capacidade de se autenticar, visualizar e contratar produtos disponíveis, enviar dados de contratação, escolher formas de pagamento e gerenciar nossos produtos. Além disso, os usuários podem cadastrar chaves SSH e realizar o deploy de um sistema operacional de forma eficiente e segura. Esta API foi projetado para simplificar e agilizar o gerenciamento de recursos proporcionando que a a Gravscale forneça uma experiência integrada e intuitiva para os usuários.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gravscale.models.create_public_ip_schema import CreatePublicIpSchema


class TestCreatePublicIpSchema(unittest.TestCase):
    """CreatePublicIpSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePublicIpSchema:
        """Test CreatePublicIpSchema
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CreatePublicIpSchema`
        """
        model = CreatePublicIpSchema()
        if include_optional:
            return CreatePublicIpSchema(
                vpc_name = '',
                address = ''
            )
        else:
            return CreatePublicIpSchema(
                vpc_name = '',
                address = '',
        )
        """

    def testCreatePublicIpSchema(self):
        """Test CreatePublicIpSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
